# -*- coding: utf-8 -*-
"""Learner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_r-ONc_FQ1U2s2EPmblDf7V8Q-2-QgF
"""

import numpy as np

class Learner:

  def __init__(self, n_arms):
    self.n_arms=n_arms
    self.t=0
    self.rewards_per_arm= x = [[] for i in range (n_arms)]
    self.collected_rewards=np.array([])

  def update_observations(self, pulled_arm, reward):
    self.rewards_per_arm[pulled_arm].append(reward)
    self.collected_rewards=np.append(self.collected_rewards,reward)